import type { Metadata } from "next";
import "./globals.css";
import "react-loading-skeleton/dist/skeleton.css";
import { Web3Provider } from "./providers";
import BottomBar from "@/components/bottom-bar";
import Topbar from "@/components/top-bar";

import { Handjet } from "next/font/google";

const handjet = Handjet({
  subsets: ["latin"],
  weight: ["400", "700"], // podés elegir los pesos que necesites
  variable: "--font-handjet", // opcional: usar como CSS variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={handjet.className}>
      <body className={`antialiased`}>
        <Web3Provider>
          <Topbar />
          {children}
          <BottomBar />
        </Web3Provider>
      </body>
    </html>
  );
}
